# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['client.py'],
    pathex=[],
    binaries=[],
    datas=[('common.py', '.')],
    hiddenimports=[
        'RNS', 'PIL', 'PIL.Image', 'customtkinter',
        'RNS.Interfaces',
        'RNS.Interfaces.Interface',
        'RNS.Interfaces.LocalInterface',
        'RNS.Interfaces.AutoInterface',
        'RNS.Interfaces.TCPInterface',
        'RNS.Interfaces.UDPInterface',
        'RNS.Interfaces.I2PInterface',
        'RNS.Interfaces.RNodeInterface',
        'RNS.Interfaces.RNodeMultiInterface',
        'RNS.Interfaces.SerialInterface',
        'RNS.Interfaces.KISSInterface',
        'RNS.Interfaces.AX25KISSInterface',
        'RNS.Interfaces.PipeInterface',
        'RNS.Interfaces.BackboneInterface',
        'RNS.Interfaces.WeaveInterface',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cipro_client-linux',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
